title: Tyler's Practice
author: Tyler
email: tmaatallah@hoes.com
description: > # this means to ignore newlines until "baseurl:"
  Hmmmmmmmm.....

# social links
twitter_username: hakunamaatallah
github_username:  hakunamaatallah

show_excerpts: true 
theme: minima
